blocks:([]
        hash:();
        strippedsize:`float$();
        size:`float$();
        weight:`float$();
        height:`long$();
        version:`long$();
        versionHex:();
        merkleroot:();
        tx:();
        time:();
        mediantime:();
        nonce:`float$();
        bits:();
        difficulty:`float$();
        chainwork:();
        previousblockhash:()
 );

