startIndex:0f;
writeFreq:10f;
chunkSize:1000f;
hdbLocation:`:.;
hdbPort:34567;
txidLocation:`$string[hdbLocation],"/txidLookup";
addressLocation:`$string[hdbLocation],"/addressLookup";
rpcUsername:"";
rpcPassword:"";
